

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class prihlasovanie extends javax.swing.JFrame {

    /**
     * Creates new form prihlasovanie
     */
    public prihlasovanie() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jTextmeno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonucitel = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextmeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jButton1.setText("prihlasit");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, -1));

        jButtonucitel.setBackground(new java.awt.Color(255, 153, 0));
        jButtonucitel.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jButtonucitel.setText("ucitel");
        jButtonucitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonucitelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonucitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 30));
        getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, 30));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel2.setText("meno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 30));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel3.setText("heslo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 190, 90, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("system na spravu rocnikovych projektov");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 460, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\simon\\Desktop\\pozadie.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, 870, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String heslo = jPasswordField3.getText();  // Zadefinuje premennú heslo a vlozí doň text
        String meno = jTextmeno.getText();  // Zadefinuje premennú meno a vlozí doň text
        if (heslo.contains("1") && meno.contains("1")) //kontroluje zhodnosť mena a hesla
        {
            jPasswordField3.setText(null); //vymaže text v poli heslo
   jTextmeno.setText(null); //vymaže text v poli meno

            domov domov = new domov(); // Zadefinuje Jframe(Domov)
            domov.show(); // Zobrazí Jframe(Domov)
            dispose(); // Zatvoí povodný Jframe
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Neplatné alebo Zle zadané prihlasovacie údaje.","LOGIN_ERROR",JOptionPane.ERROR_MESSAGE); //Error message
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonucitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonucitelActionPerformed
 String heslo = jPasswordField3.getText();  // Zadefinuje premennú heslo a vlozí doň text
        String meno = jTextmeno.getText();  // Zadefinuje premennú meno a vlozí doň text
        if (heslo.contains("2") && meno.contains("2")) //kontroluje zhodnosť mena a hesla
        {
            jPasswordField3.setText(null); //vymaže text v poli heslo
   jTextmeno.setText(null); //vymaže text v poli meno

          ucitel2  ucitel2  = new  ucitel2 (); // Zadefinuje Jframe(Domov)
             ucitel2 .show(); // Zobrazí Jframe(Domov)
            dispose(); // Zatvoí povodný Jframe
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Neplatné alebo Zle zadané prihlasovacie údaje.","LOGIN_ERROR",JOptionPane.ERROR_MESSAGE); //Error message
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonucitelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prihlasovanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prihlasovanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prihlasovanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prihlasovanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prihlasovanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonucitel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextmeno;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
